
controller_frequency: 10.0
default_task_wrapper: generic

plugins:
  TaskToTaskWorkflow:
    dubins: dubins_curves/Dubins
    preview: dubins_curves/Dubins
    navcoreplanner: project11_navigation/NavCorePlanner
    alexplanner: alex_path_planner/AlexPathPlanner
    dubins_planner: dubins_planner/DubinsPlanner
  TaskToTwistWorkflow:
    executive: project11_navigation/ExecuteTask
    transit: project11_navigation/TaskToTwistStack
    hover: hover/Hover
    path_follower: path_follower/PathFollower
    survey_line: project11_navigation/TaskToTwistStack
  TaskListToTaskListWorkflow:
    task_connector: project11_navigation/TaskConnector
  TaskListToTwistWorkflow:
    task_manager: project11_navigation/TaskManager
  TaskWrapper:
    generic: project11_navigation/GenericTask
    goto: project11_navigation/GotoTask
    hover: project11_navigation/HoverTask
    survey_area: project11_navigation/SurveyAreaTask
    survey_line: project11_navigation/SurveyLineTask
    transit: project11_navigation/TransitTask

TaskToTwistWorkflow/executive:
  handlers:
    foo: bar

TaskToTwistWorkflow/path_follower:
  pid:
    upper_limit: 90
    lower_limit: -90
    windup_limit: 50

TaskToTwistWorkflow/transit:
  steps:
    - dubins_planner
  last_step: path_follower

TaskToTwistWorkflow/survey_line:
  last_step: path_follower

TaskToTaskWorkflow/preview:
  output_task_name: preview_trajectory

TaskToTaskWorkflow/alexplanner:
  time_horizon: 300.0
  planning_time: 5.0